Adds ubuntu-kinetic support
citusdata/packaging pull request #1009
Opened 2022-11-18 09:24 UTC by gurkanindibay

2022-11-26 17:59 UTC, hanefi requested changes
The scripts in `scripts` directory have missing `+x` permissions. I think they should be 755 instead of 644.

The same mistake is there on many other files. The template files for these scripts have the correct permissions but somehow they are wrong on many of the other directories such as `ubuntu-kinetic-all/scripts`.

I suggest that you do it correctly, and create a mechanism to check that they are not broken again.

2022-11-28 16:18 UTC, gurkanindibay commented
> The scripts in `scripts` directory have missing `+x` permissions. I think they should be 755 instead of 644.
> 
> The same mistake is there on many other files. The template files for these scripts have the correct permissions but somehow they are wrong on many of the other directories such as `ubuntu-kinetic-all/scripts`.
> 
> I suggest that you do it correctly, and create a mechanism to check that they are not broken again.

I removed all the scripts under dockerfile directory and updated update_dockerfile not to update the useless scripts anymore.
since scripts under ./scripts directory are actually being copied into docker images.

2022-11-29 21:02 UTC, hanefi commented
> scripts under ./scripts directory are actually being copied into docker images in update_images script

Can you share a link to the lines of code that does this? I didn't know we did that.

2022-11-29 21:02 UTC, hanefi approved these changes

2022-11-30 05:46 UTC, merged