Adds fallback address for debian releases
citusdata/packaging pull request #1043
Opened 2023-04-13 03:53 UTC by gurkanindibay

2023-04-13 09:13 UTC, hanefi requested changes
After addressing the comments, can you apply the same patch to other 3 `deb.sh` files as well?

2023-04-13 09:13 UTC, hanefi commented on community/deb.sh
> -  # create an apt config file for this repository
Why did we remove this comment?

2023-04-13 09:13 UTC, hanefi commented on community/deb.sh
> +  if [ "${os}" = "debian" ] && [ "$curl_exit_code" -ne "0" ]; then
Can we add a comment before this conditional to explain why we need such a change?

2023-04-13 12:38 UTC, hanefi submitted a review, later dismissed

2023-04-13 15:09 UTC, gurkanindibay commented on community/deb.sh
> -  # create an apt config file for this repository
Removed mistakenly. Added again

2023-04-14 01:50 UTC, hanefi approved these changes

2023-04-14 07:31 UTC, merged