Release pg_auto_failover-enterprise 1.0.3
citusdata/packaging pull request #337
Opened 2019-08-01 07:25 UTC by mtuncer

2019-08-01 09:58 UTC, thanodnl commented
Last time I tried installing the debian packages for enterprise there was a problem with the dependencies. I don't see any changes for that now. Did you test installing the packages after building them locally, and does that work?

2019-08-01 09:59 UTC, mtuncer commented
No I did not test debians
Let me do that

2019-08-01 10:00 UTC, thanodnl requested changes

2019-08-01 10:00 UTC, thanodnl commented on debian/changelog
> +  * Fix Terminate conflicting queries at failover time (#194)
debian changelogs should not contain the changelog of the application, but instead the changelog to the packaging. I have made that mistake in the past as well :).

Hence the boring changlog here that reads something like `Official release of <package> <version>`

2019-08-01 13:48 UTC, mtuncer commented
well I was not able to install pg_auto_failover package via dpkg -i. It complained about missing dependencies.
I run `apt install --fix-broken` after the failure at it installed fine.

2019-08-02 12:23 UTC, thanodnl commented
Ok, let me check and reproduce this on debian

2019-08-02 13:11 UTC, thanodnl approved these changes

2019-08-02 13:15 UTC, merged