Support pg13 in packaging pipeline
citusdata/packaging pull request #532
Opened 2020-11-02 13:15 UTC by onurctirtir

Apply base changes for pg13 support at e67b522
Then run update_dockerfiles to apply base changes at 9c20cb5

Also, as CentOS/OracleLinux 6 doesn't have essential pg13 packages, disable updating "package builder docker image" for those distros, and disable citus package building as well at 52cc808

Now built some docker images as well, I will test if packaging works fine with pg13 for some random distros.

2020-11-03 08:14 UTC, hanefi commented
I suggest you remove the new folders for el6 & PG13 that do not build because of missing packages in PGDG repos.

Also I suggest you keep the changes for making exceptions for EL6 in a separate commit, so that we can revert it once the PGDG packages are there.

2020-11-03 08:38 UTC, onurctirtir commented
> I suggest you remove the new folders for el6 & PG13 that do not build because of missing packages in PGDG repos.

But then, ci wouldn't pass ?


> Also I suggest you keep the changes for making exceptions for EL6 in a separate commit, so that we can revert it once the PGDG packages are there.

Agree 6e4b608

2020-11-03 10:53 UTC, hanefi commented
> > I suggest you remove the new folders for el6 & PG13 that do not build because of missing packages in PGDG repos.
> 
> But then, ci wouldn't pass ?

If you add some logic for excluding EL6&PG13 combination in the lines below, then CI would pass I think.
https://github.com/citusdata/packaging/blob/6e4b608a9d41d2efdce1b70f386ee85a89965fb4/update_dockerfiles#L92-L94

2020-11-10 08:09 UTC, hanefi requested changes

2020-11-10 08:09 UTC, hanefi commented on .travis.yml
> +    #- TARGET_PLATFORM=debian,jessie
Debian Jessie EOL'd on June 30, 2020. We can safely remove this line.

2020-11-10 08:09 UTC, hanefi commented on build_packages
> +        if [[ "${os}" = 'debian' ]] && [[ "${release}" = 'jessie' ]]; then
Debian Jessie EOL'd. We can remove these changes

2020-11-10 08:44 UTC, hanefi commented on .travis.yml
> +    #- TARGET_PLATFORM=debian,jessie
On second thought, we are able to create PG11 and PG12 packages for Debian Jessie.

Should we keep creating packages for Jessie only for a limited set of PG versions?

2020-11-10 09:19 UTC, onurctirtir commented on .travis.yml
> +    #- TARGET_PLATFORM=debian,jessie
>Should we keep creating packages for Jessie only for a limited set of PG versions?

I think yes

2020-11-10 10:31 UTC, hanefi requested changes
I checked all CI builds, and they are ok except Debian Jessie is missing.

If we do not drop support for Debian Jessie, we should still keep it in CI. You can modify scripts used in CI to exclude PG13 builds for Debian Jessie, I guess.

2020-11-10 11:54 UTC, hanefi commented on update_dockerfiles
> +            fi
nit, trailing whitespace

2020-11-10 12:03 UTC, onurctirtir commented on update_dockerfiles
> +            fi
addressed

2020-11-10 13:53 UTC, hanefi approved these changes
:shipit:

2020-11-10 14:15 UTC, merged