Update deb and rpm scripts to use PG13
citusdata/packaging pull request #545
Opened 2020-11-12 12:30 UTC by onurctirtir

2020-11-12 12:40 UTC, onurctirtir commented
Tested on Ubuntu 18.04, works fine

2020-11-13 09:29 UTC, hanefi commented on community-nightlies/deb.sh
> +      echo "PGDG doesn't postgresql-13 package for operating system"
```suggestion
      echo "PGDG repositories don't have PostgreSQL 13 packages for your operating system"
      echo
```

2020-11-13 09:58 UTC, onurctirtir commented on community-nightlies/deb.sh
> +      echo "PGDG doesn't postgresql-13 package for operating system"
addressed

2020-11-13 10:48 UTC, hanefi requested changes

2020-11-13 10:48 UTC, hanefi commented on community-nightlies/rpm96.sh
> +    if ! yum info -q postgresql13-server &> /dev/null; then
`(deb|rpm)96.sh` scripts are for installing PG 9.6 and supported extensions.

AFAIK, they are outdated and can be removed. It does not makes sense to me that we are checking for PG13 packages for a script that aims to install PG9.6 repos.

Let's keep these files as is, and maybe remove them in a seperate PR.

2020-11-13 12:30 UTC, hanefi approved these changes

2020-11-13 12:40 UTC, merged