Adds update_package_properties and build_packages in pg-auto-failover-enterprise
citusdata/packaging pull request #713
Opened 2021-08-10 11:13 UTC by gurkanindibay

pipelines

2021-08-21 15:01 UTC, hanefi commented
Should be blocked until #709 gots merged. After that one is complete, you can update this PR.

2021-08-26 08:47 UTC, hanefi requested changes
After addressing my comments, please compare Github Workflow definitions in `all-pgautofailover` branch with the ones in here.

2021-08-26 08:47 UTC, hanefi commented on .github/workflows/build-package.yml
> +        run: git clone -b issue_156 --depth=1  https://github.com/citusdata/tools.git tools
needs a tag

2021-08-26 08:47 UTC, hanefi commented on .github/workflows/build-package.yml
> +          - ubuntu/xenial
Does Xenial build properly?

2021-08-26 08:47 UTC, hanefi commented on .github/workflows/build-package.yml
> +          --main_branch ${MAIN_BRANCH}
inconsistent use of quotations

2021-08-26 08:47 UTC, hanefi commented on .github/workflows/update_package_properties.yml
> +          --exec_path "$(pwd)"
inconsistent use of quotations

2021-08-26 08:47 UTC, hanefi commented on .github/workflows/update_package_properties.yml
> +        run: git clone -b issue-149 --depth=1  https://github.com/citusdata/tools.git tools
needs a tag

2021-08-26 09:07 UTC, gurkanindibay commented on .github/workflows/build-package.yml
> +          - ubuntu/xenial
yes

2021-08-26 09:07 UTC, gurkanindibay commented on .github/workflows/build-package.yml
> +        run: git clone -b issue_156 --depth=1  https://github.com/citusdata/tools.git tools
Fixed

2021-08-26 09:07 UTC, gurkanindibay commented on .github/workflows/build-package.yml
> +          --main_branch ${MAIN_BRANCH}
Fixed

2021-08-26 09:07 UTC, gurkanindibay commented on .github/workflows/update_package_properties.yml
> +        run: git clone -b issue-149 --depth=1  https://github.com/citusdata/tools.git tools
Fixed

2021-08-26 09:07 UTC, gurkanindibay commented on .github/workflows/update_package_properties.yml
> +          --exec_path "$(pwd)"
Fixed

2021-08-26 09:27 UTC, hanefi requested changes

2021-08-26 09:27 UTC, hanefi commented on .github/workflows/build-package.yml
> +          --main_branch "${MAIN_BRANCH}"
inconsistent use of quotation marks.

`--platform "${{ matrix.platform }}"`

or 

`--platform ${{ matrix.platform }}`

make up your mind, and stick to it.

2021-08-26 09:27 UTC, hanefi commented on .github/workflows/build-package.yml
> +        run: git clone -b v0.8.1 --depth=1  https://github.com/citusdata/tools.git tools
```suggestion
        run: git clone -b v0.8.1 --depth=1 https://github.com/citusdata/tools.git tools
```

2021-08-26 09:27 UTC, hanefi commented on .github/workflows/build-package.yml
> +          python -m  tools.packaging_automation.citus_package \
```suggestion
          python -m tools.packaging_automation.citus_package \
```

2021-08-26 09:27 UTC, hanefi commented on .github/workflows/build-package.yml
> +          python -m  tools.packaging_automation.upload_to_package_cloud \
```suggestion
          python -m tools.packaging_automation.upload_to_package_cloud \
```

2021-08-26 09:27 UTC, hanefi commented on .github/workflows/update_package_properties.yml
> +        run: git clone -b v0.8.1  --depth=1  https://github.com/citusdata/tools.git tools
```suggestion
        run: git clone -b v0.8.1 --depth=1 https://github.com/citusdata/tools.git tools
```

2021-08-26 09:27 UTC, hanefi commented on .github/workflows/build-package.yml
> +    branches: "**"
```suggestion
    branches:
    - "**"
```

2021-08-26 09:27 UTC, hanefi commented on .github/workflows/build-package.yml
> +  PACKAGE_ENCRYPTION_KEY: ${{ secrets.PACKAGE_ENCRYPTION_KEY }}
IIRC, Github recommends that all secrets should be stored in env variables, just like this one here.

Does that make sense to do? What do you think?

2021-08-26 09:27 UTC, hanefi commented on .github/workflows/build-package.yml
> +          - ubuntu/xenial
this is a surprise to me as we were not able to build packages on PGAF community

2021-08-26 09:28 UTC, hanefi commented on .github/workflows/build-package.yml
> +          --main_branch ${MAIN_BRANCH}
I do not think so. Please take a look at my other comments.

2021-08-26 09:28 UTC, hanefi commented on .github/workflows/update_package_properties.yml
> +          --exec_path "$(pwd)"
I do not think so. Please take a look at my other comments.

2021-08-26 09:32 UTC, gurkanindibay commented on .github/workflows/build-package.yml
> +          - ubuntu/xenial
it also failed this time I needed to remove it

2021-08-26 09:39 UTC, hanefi commented on .github/workflows/build-package.yml
> +  PACKAGE_ENCRYPTION_KEY: ${{ secrets.PACKAGE_ENCRYPTION_KEY }}
This comment affect all branches where we started to use GH actions. I opened an issue for this task: https://github.com/citusdata/packaging/issues/740

2021-08-26 09:44 UTC, gurkanindibay commented on .github/workflows/build-package.yml
> +          --main_branch "${MAIN_BRANCH}"
github variables don't need to be in quotation marks. So I don't put quotation marks.For environment variables quotation marks are needed

2021-08-26 09:44 UTC, gurkanindibay commented on .github/workflows/build-package.yml
> +  PACKAGE_ENCRYPTION_KEY: ${{ secrets.PACKAGE_ENCRYPTION_KEY }}
I will check all of them I missed this oneç Normally I'm trying to be careful
Fixed this one

2021-08-26 16:12 UTC, hanefi commented on .github/workflows/build-package.yml
> +          --build_type 'release' \
```suggestion
          --build_type "release" \
```

2021-08-26 16:12 UTC, hanefi commented on .github/workflows/update_package_properties.yml
> +          git config --global user.name "${{ github.event.inputs.name }}"
https://github.com/citusdata/packaging/pull/713#discussion_r696468145 :

> Github variables don't need to be in quotation marks. So I don't put quotation marks. For environment variables quotation marks are needed

Does that mean, that you should have the following here:
```suggestion
          git config --global user.email ${{ github.event.inputs.microsoft_email }} && \
          git config --global user.name ${{ github.event.inputs.name }}
```

I do not like or promote your idea on when to use double quotes. I think that we should always use double quote to prevent globbing and word splitting. See: https://github.com/koalaman/shellcheck/wiki/SC2086

For the time being, I am ok with anything as long as you are consistent and have a policy about this.

2021-08-27 07:26 UTC, gurkanindibay commented on .github/workflows/build-package.yml
> +          --main_branch "${MAIN_BRANCH}"
I looked into a little bit and using double quotes for Github Actions parameters as a standard is better way in bash scripts. Changing like this

2021-08-27 07:31 UTC, gurkanindibay commented on .github/workflows/build-package.yml
> +          --build_type 'release' \
Fixed as you suggested

2021-08-27 07:32 UTC, gurkanindibay commented on .github/workflows/update_package_properties.yml
> +          git config --global user.name "${{ github.event.inputs.name }}"
Used double quotes as a standard

2021-08-27 07:32 UTC, gurkanindibay commented on .github/workflows/update_package_properties.yml
> +          --exec_path "$(pwd)"
Used double quotes as standard

2021-08-27 07:32 UTC, gurkanindibay commented on .github/workflows/build-package.yml
> +          --main_branch ${MAIN_BRANCH}
Used double quotes as standard

2021-08-27 08:40 UTC, hanefi reviewed
Let's remove ubuntu/xenial from travis tests as well

2021-08-27 08:40 UTC, hanefi commented on .github/workflows/build-package.yml
> +        run: sudo apt-get update && python -m pip install -r tools/packaging_automation/requirements.txt
```suggestion
        run: python -m pip install -r tools/packaging_automation/requirements.txt
```

no need to do this again.

2021-08-31 12:34 UTC, hanefi approved these changes

2021-09-01 06:52 UTC, gurkanindibay commented on .github/workflows/build-package.yml
> +        run: sudo apt-get update && python -m pip install -r tools/packaging_automation/requirements.txt
Fixed

2021-09-01 06:57 UTC, merged